### ISSUE TITLE
Cache Unity installation files

### ISSUE THREAD

**Issue by rbetik12** [buildalon/unity-setup#12]
Hi!

Have you ever considered testing Github Action cache for Unity installation to make builds faster. Now your CI pipeline redownloads Unity each time you lauch it.

I tried to do that myself, but had some problems with that. I don't know every location of the Unity installation I must cache to preserve Unity Editor. Do you have that information for Ubuntu or have you ever tested that?

**Comment by StephenHodgson** [comment]
@rbetik12 the cache is something you can completely control yourself in a few different ways.

1. Use [Buildalon runner](https://www.buildalon.com), which does local cache and uses Unity Accelerator
2. Add cache step to your workflow
3. Use self hosted [Unity Accelerator](https://docs.unity3d.com/Manual/UnityAccelerator.html) instance and specify its usage in the cli input of your build steps

**Comment by StephenHodgson** [comment]
> Do you have that information for Ubuntu or have you ever tested that?

Yes all of our actions are [vetted and tested](https://github.com/buildalon/unity-setup/actions/workflows/validate.yml) on GitHub hosted runners as well as our Buildalon runners :)

**Comment by StephenHodgson** [comment]
> Now your CI pipeline redownloads Unity each time you launch it.

With our Buildalon runners or a self hosted runner this is not the case :)

**Comment by StephenHodgson** [comment]
@rbetik12 if you have any other questions be sure to reach out on our [Discord](https://discord.gg/VM9cWJ9rjH) :)
